### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by wcjj1236** [w-m/3dgs-compression-survey#10]
Hey, I was wondering how do people calculate for PSNR of some specific dataset, like for TanksAndTemple. Do they calculate the average PSNR for all scenes in this dataset or just pick up the best PSNR among train and truck scenes in TanksAndTemple?

**Comment by myla** [comment]
Hi,
thank you for asking. The calculated PSNR are supposed to be averages. You can find the included scenes for each dataset in the readme [here](https://github.com/w-m/3dgs-compression-survey?tab=readme-ov-file#including-your-own-results). We currently in the process of making sure all contributions are using the same scenes to ensure comparability.
Best,
Milena
