### ISSUE TITLE
Add CompGS

### ISSUE THREAD

**Issue by ZhiyeTang** [w-m/3dgs-compression-survey#11]
A new approach [CompGS](https://github.com/LiuXiangrui/CompGS) for 3DGS compression published on ACM MM 2024 has recently released the code. Please consider adding it to your table.

Otherwise, [ContextGS](https://github.com/wyf0912/ContextGS) is accepted to NeurIPS 2024, but the code is not accessible yet.

**Comment by w-m** [comment]
Thanks for bringing these methods to our attention! If you are in contact with the authors, please ask them to provide their results in the format documented here: https://github.com/w-m/3dgs-compression-survey?tab=readme-ov-file#including-your-own-results

With [CompGS](https://github.com/LiuXiangrui/CompGS), there's now a naming conflict with [Navaneet et. al.](https://ucdvision.github.io/compact3d/). We currently list Navaneet et. al. as CompGS, as they use that on their web page and plots. I guess we should use "Compact3D" then for Navaneet.

**Comment by myla** [comment]
ContextGS is fully merged. CompGS data is also added, it is missing a summary, will add that as soon as possible.
