### ISSUE TITLE
Add RDO-Gaussian: End-to-End Rate-Distortion Optimized 3D Gaussian Representation

### ISSUE THREAD

**Issue by rdogaussian** [w-m/3dgs-compression-survey#2]
[http://arxiv.org/abs/2406.01597](url)

3D Gaussian Splatting (3DGS) has become an emerging technique with remarkable potential in 3D representation and image rendering. However, the substantial storage overhead of 3DGS significantly impedes its practical applications. In this work, we formulate the compact 3D Gaussian learning as an end-to-end Rate-Distortion Optimization (RDO) problem and propose RDO-Gaussian that can achieve flexible and continuous rate control. RDO-Gaussian addresses two main issues that exist in current schemes: 1) Different from prior endeavors that minimize the rate under the fixed distortion, we introduce dynamic pruning and entropy-constrained vector quantization (ECVQ) that optimize the rate and distortion at the same time. 2) Previous works treat the colors of each Gaussian equally, while we model the colors of different regions and materials with learnable numbers of parameters. We verify our method on both real and synthetic scenes, showcasing that RDO-Gaussian greatly reduces the size of 3D Gaussian over 40×, and surpasses existing methods in rate-distortion performance.

**Comment by paulbzm** [comment]
Please provide your results in your repository, following the instructions in our README file in the section "Including your own Results".

**Comment by paulbzm** [comment]
Hi @rdogaussian, do you have an estimated timeline for when the results will be available in your repository? Please let me know if you need any further details or assistance in the process.

**Comment by rdogaussian** [comment]
We have provided the results in our repository: [https://github.com/USTC-IMCL/RDO-Gaussian](https://github.com/USTC-IMCL/RDO-Gaussian). Please update the results of our method, thank you!

**Comment by paulbzm** [comment]
Thank you, your results are now available on our website!
