### ISSUE TITLE
Submit a result with only MipNeRF 360

### ISSUE THREAD

**Issue by liruilong940607** [w-m/3dgs-compression-survey#6]
Hey, Is it ok to submit a result on only MipNeRF 360 dataset?

We have been integrating some compression ideas in gsplat (https://github.com/nerfstudio-project/gsplat/pull/309) and things seem to working pretty well. So would love to submit our results to this leaderboard!

**Comment by liruilong940607** [comment]
I put up a PR about it in #7

**Comment by paulbzm** [comment]
Thank you for your interest in participating in our survey! We generally require results across multiple datasets for evaluation to ensure a comprehensive comparison. 

Would it be possible for you to provide results for the other datasets as well? Or are you facing any challenges in doing that? Otherwise, I could also try to run the missing evaluations myself.

Your approach looks very promising, and we look forward to including it in our review!

**Comment by liruilong940607** [comment]
Hey!

I just realized we were evaluating on 7 instead of 9 scenes of MipNeRF360, after fixing it the performance is not that crazy as before, but the ranking seems still be good. (see the PR)

Also I guess this is something that I would like to confirm with you, are all methods on the leaderboard tested on all 9 scenes of MipNeRF360? I'm asking because there was a period that two of the MipNeRF360 scenes (treehill flowers) were not open to the public so there are some papers (at least in NeRF literature) only evaluate on the 7 scenes that were publicly available.

For 3DGS, since the inria's official codebase was evaluated on all 9 scenes, I assume the papers based on that code base might also be evaluating on all 9 scenes. But just want to check out with you to see if you have looked into this already.

As for the full evaluation on other datasets, unfortunately our codebase wasn't setup to support other data parser. But it should be very doable. I probably won't have time recently to support all other three datasets. So which dataset(s) do you think I should at least include for benchmarking the compression? 

Also we (the gsplat project) are always open to contributions if you are interested!

**Comment by paulbzm** [comment]
Yes, all methods on the leaderboard are supposed to be evaluated on all 9 scenes of MipNeRF360, so thank you for updating your results. We are however currently in the process of ensuring that all approaches listed in the survey do adhere to this.
 
Regarding the selection of additional datasets, I think providing results for Tanks and Temples (Train and Truck scenes) would suffice for inclusion in the survey. I will also look into integrating the remaining datasets once I have time for this.
