### ISSUE TITLE
Scaffold-GS metrics only uses 7 scenes.

### ISSUE THREAD

**Issue by jefequien** [w-m/3dgs-compression-survey#9]
The Scaffold-GS PSNR of 28.84 is across 7 scenes, not 9 as used by the rest of the table. It should be 27.50 as reported by the HAC paper which uses all 9 scenes.

https://github.com/w-m/3dgs-compression-survey/blob/5b1b110a899c44482c2ace0758bcdfcfeba5a4bc/results/MipNeRF360.csv#L12

Screenshots from [Scaffold-GS](https://arxiv.org/pdf/2312.00109) paper. 
<img width="279" alt="Screenshot 2024-09-04 at 8 00 10 AM" src="https://github.com/user-attachments/assets/0271daec-d662-4350-84c9-5fff9bbe176c">
<img width="331" alt="Screenshot 2024-09-04 at 8 01 01 AM" src="https://github.com/user-attachments/assets/09efcb81-28ce-46c8-a2e4-03850fd572a3">

Screenshots from [HAC](https://arxiv.org/pdf/2403.14530) paper.
<img width="606" alt="Screenshot 2024-09-04 at 8 02 58 AM" src="https://github.com/user-attachments/assets/15af35f6-c89b-4992-9d1e-81b1f4bd8f66">

**Comment by w-m** [comment]
Thanks, Jeffrey, for the report!

@paulbzm then please use the numbers from the HAC paper for Scaffold-GS in the table

@myla maybe highlight this point in the author mailing to the Scaffold-GS authors

**Comment by jefequien** [comment]
@w-m For your awareness, I also opened this issue. 
https://github.com/YihangChen-ee/HAC/issues/14

**Comment by paulbzm** [comment]
Thanks @jefequien , the results are updated now!

**Comment by jefequien** [comment]
@paulbzm The HAC authors responded to my [issue](https://github.com/YihangChen-ee/HAC/issues/14). You can use the new HAC numbers in the survey. Also, the Scaffold-GS numbers are likely incorrect because they do not consider MipNeRF's data factor.

**Comment by paulbzm** [comment]
Thanks again @jefequien !
